Fix XDocument.Load on .NET 3.5
The XDocument.Load doesn't accept stream on .NET 3.5 so wrap it using accepted XmlReader.
More info: https://stackoverflow.com/questions/3281714/how-to-read-xml-file-using-system-io-stream-with-linq

This commit will fix the following CI error:
BuildMetadataFromXml.cs(90,43): error CS1503: Argument 1: cannot convert from 'System.IO.Stream' to 'string' [C:\projects\libphonenumber-csharp\csharp\PhoneNumbers\PhoneNumbers.csproj]