Use embedded xml resources for .NET 3.5 (#80)
* Use embedded xml resources for .NET 3.5

Since 6a75a40218b we are not trying to use dll embedded resources.
Instead we are tying to load directly the XDocument from filesystem.

This commit should fix the problem by using embedded dll resources.
Although further tests required to ensure that external resources still work.

* Remove not required endif

* Fix XDocument.Load on .NET 3.5

The XDocument.Load doesn't accept stream on .NET 3.5 so wrap it using accepted XmlReader.
More info: https://stackoverflow.com/questions/3281714/how-to-read-xml-file-using-system-io-stream-with-linq

This commit will fix the following CI error:
BuildMetadataFromXml.cs(90,43): error CS1503: Argument 1: cannot convert from 'System.IO.Stream' to 'string' [C:\projects\libphonenumber-csharp\csharp\PhoneNumbers\PhoneNumbers.csproj]

* Import System.Xml for .NET 3.5

* Fix XDocument.Load using XmlTextReader

As suggested by @neuroid.

* cosmetic: Fix white space